$ANSIBLE_VAULT;1.1;AES256
66626638626465316532663336343433636632303332396430623038613937353639646534663536
3365383633316231643262323166333136326137356262320a326438663061633862326335633234
63336430306332306566633637646437346231643230326235313861343531616166366230326230
3233396536313837630a663336346464653065633630653664386338343665316366643461666165
31343938653233303336653337393762353836636132303730656266646362303363623832393032
63376164323830333563623632633566376539353338633739356262363334373431336539356561
33396337353233636637393863613563616236363535376464663065366437653633616530343963
62376138633539303931
